#!/usr/bin/env tsx
/**
 * Sandra onboarding wizard — interactive setup helper.
 * Run: pnpm tsx scripts/wizard.ts
 */
import { createInterface } from "readline/promises";
import { stdin as input, stdout as output } from "process";
import { writeFile, readFile } from "fs/promises";
import { join } from "path";

const rl = createInterface({ input, output });

function bold(s: string): string { return `\x1b[1m${s}\x1b[0m`; }
function cyan(s: string): string { return `\x1b[36m${s}\x1b[0m`; }
function green(s: string): string { return `\x1b[32m${s}\x1b[0m`; }
function yellow(s: string): string { return `\x1b[33m${s}\x1b[0m`; }

async function ask(question: string, defaultVal?: string): Promise<string> {
  const hint = defaultVal ? ` [${defaultVal}]` : "";
  const answer = await rl.question(`  ${cyan("?")} ${question}${hint}: `);
  return answer.trim() || defaultVal || "";
}

async function askYN(question: string, defaultYes = true): Promise<boolean> {
  const hint = defaultYes ? "Y/n" : "y/N";
  const answer = await rl.question(`  ${cyan("?")} ${question} (${hint}): `);
  if (!answer.trim()) return defaultYes;
  return answer.trim().toLowerCase().startsWith("y");
}

async function main(): Promise<void> {
  console.log("\n" + bold("═══════════════════════════════════════"));
  console.log(bold("  Sandra — Onboarding Wizard"));
  console.log(bold("═══════════════════════════════════════") + "\n");
  console.log("This wizard will help you configure Sandra for the first time.");
  console.log("Values will be saved to " + yellow(".env.local") + " (never committed to git).\n");

  // Check if .env.local already exists
  const envPath = join(process.cwd(), ".env.local");
  let existing: Record<string, string> = {};
  try {
    const content = await readFile(envPath, "utf-8");
    for (const line of content.split("\n")) {
      const [k, ...v] = line.split("=");
      if (k?.trim() && !k.startsWith("#")) existing[k.trim()] = v.join("=").trim();
    }
    console.log(yellow("  ⚠ .env.local already exists — existing values shown as defaults\n"));
  } catch { /* first run */ }

  const config: Record<string, string> = { ...existing };

  // AWS
  console.log(bold("\n── AWS Configuration ──────────────────"));
  config["AWS_REGION"] = await ask("AWS region", config["AWS_REGION"] ?? "us-east-1");
  const useSecretsManager = await askYN("Use AWS Secrets Manager?", true);
  if (useSecretsManager) {
    config["SECRETS_NAME"] = await ask("Secrets Manager secret name", config["SECRETS_NAME"] ?? "sandra/prod");
  }

  // Database
  console.log(bold("\n── Database ───────────────────────────"));
  config["DATABASE_URL"] = await ask("PostgreSQL connection URL", config["DATABASE_URL"] ?? "postgresql://localhost:5432/sandra");

  // Telegram
  console.log(bold("\n── Telegram ───────────────────────────"));
  const useTelegram = await askYN("Configure Telegram bot?", true);
  if (useTelegram) {
    config["TELEGRAM_BOT_TOKEN"] = await ask("Telegram bot token", config["TELEGRAM_BOT_TOKEN"]);
    config["TELEGRAM_WEBHOOK_SECRET"] = await ask("Telegram webhook secret", config["TELEGRAM_WEBHOOK_SECRET"] ?? generateSecret());
  }

  // Domain & TLS
  console.log(bold("\n── Server ─────────────────────────────"));
  config["DOMAIN"] = await ask("Your domain (e.g. sandra.example.com)", config["DOMAIN"]);
  config["PORT"] = await ask("API port", config["PORT"] ?? "3000");

  // Optional
  const configureOptional = await askYN("\nConfigure optional services (WhatsApp, Perplexity, etc.)?", false);
  if (configureOptional) {
    config["PERPLEXITY_API_KEY"] = await ask("Perplexity API key (for research)", config["PERPLEXITY_API_KEY"]);
    config["OLLAMA_BASE_URL"] = await ask("Ollama URL (for local LLM)", config["OLLAMA_BASE_URL"] ?? "http://localhost:11434");
    config["WEB_AUTH_TOKENS"] = await ask("Web chat auth tokens (comma-separated)", config["WEB_AUTH_TOKENS"]);
  }

  // Security
  config["DATA_ENCRYPTION_KEY"] = config["DATA_ENCRYPTION_KEY"] ?? generateHex(32);

  // Write .env.local
  const lines = ["# Sandra configuration — generated by wizard", "# DO NOT COMMIT THIS FILE\n"];
  for (const [k, v] of Object.entries(config)) {
    if (v) lines.push(`${k}=${v}`);
  }
  await writeFile(envPath, lines.join("\n") + "\n");

  console.log("\n" + green("✓ Configuration saved to .env.local"));
  console.log(green("✓ Run " + bold("pnpm build && pnpm db:migrate") + " to complete setup"));
  console.log(green("✓ Then run " + bold("./scripts/dev.sh") + " to start Sandra\n"));

  rl.close();
}

function generateSecret(): string {
  return Array.from(crypto.getRandomValues(new Uint8Array(16)))
    .map((b) => b.toString(16).padStart(2, "0")).join("");
}

function generateHex(bytes: number): string {
  return Array.from(crypto.getRandomValues(new Uint8Array(bytes)))
    .map((b) => b.toString(16).padStart(2, "0")).join("");
}

main().catch((err) => {
  console.error("Wizard failed:", err instanceof Error ? err.message : String(err));
  process.exit(1);
});
